apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patchesStrategicMerge:
  - central-infrastructure-management.yaml

resources:
  - ../../base
  - ingress-controller.yaml
  - route.yaml
  - crb.yaml