apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patchesStrategicMerge:
  - central-infrastructure-management.yaml
  - ingress-controller.yaml
  # - route-host-patch.yaml
  - router-type-patch.yaml

bases:
  - ../../base