# temporary fix for patch operator svc having a different host name
kind: Service
apiVersion: v1
metadata:
  name: patch-operator-controller-manager-service-fix
  namespace: patch-operator
spec:
  ports:
    - name: '443'
      protocol: TCP
      port: 443
      targetPort: 9443
  internalTrafficPolicy: Cluster
  selector:
    control-plane: patch-operator
  host: patch-operator-controller-manager-service.patch-operator.svc.local
