apiVersion: operators.coreos.com/v1alpha2
kind: OperatorGroup
metadata:
  name: external-secrets
  namespace: external-secrets
labels:
    app.kubernetes.io/instance: namespace-external-secrets
spec:
  targetNamespaces: 
  - external-secrets