apiVersion: operator.cert-manager.io/v1alpha1
kind: CertManager
metadata:
  annotations:
    operator-sdk/primary-resource: /cert-manager-webhook
    operator-sdk/primary-resource-type: ValidatingWebhookConfiguration.admissionregistration.k8s.io
  name: cert-manager
  namespace: openshift-operators
  finalizers:
    - uninstall-helm-release
spec: {}