apiVersion: batch/v1
kind: Job
metadata:
  name: aap-controller-console-link
  namespace: openshift-gitops
spec:
  template:
    spec:
      serviceAccountName: openshift-gitops-otp-argocd-application-controller
      containers:
      - name: syncset-{{ .Values.clusterClaimName }}
        image: quay.io/openshift/origin-cli:v3.11
        command: ["/bin/bash"]
        args:
        - -c
        - |-
          # if aap controller console link already exists, exit 0
          # else, wait until route `automation-hub` in `aap` is available
          # create a new console link that ArgoCD can track using this job's owner reference
      restartPolicy: OnFailure
  backoffLimit: 2