apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: controller-postgres-access
spec:
  refreshInterval: 24h0m0s
  secretStoreRef:
    name: cluster
    kind: ClusterSecretStore
  target:
    name: controller-postgres-access
    creationPolicy: Owner
  dataFrom:
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        key: 2abc61c3-13ef-0e8b-3853-9583d0e6a5fb
