---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources: 
  - automationcontroller.yaml
  - grant-aap-default-sa-privileged.yaml
  # - consolelink.yaml
  # - controller-postgres-access.yaml
  # - controller-postgres-bundle-ca-cert.yaml