apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - rbac.yaml
  - secretstore-crd.yaml
  - secretstore.yaml
  - externalsecret-crd.yaml
  - sso-configs-es.yaml
  - keycloak-pre-processing-job.yaml