# Source: https://github.com/redhat-cop/global-load-balancer-operator/blob/master/config/operatorhub/operator.yaml
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: global-load-balancer-operator
  namespace: global-load-balancer-operator
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: global-load-balancer-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: global-load-balancer-operator
  namespace: global-load-balancer-operator
spec:
  targetNamespaces: []