apiVersion: redhatcop.redhat.io/v1alpha1
kind: Patch
metadata:
  name: patch-label-argocd-clusters
  namespace: openshift-gitops
spec:
  serviceAccountRef:
    name: default
  patches:
    patch-gitops-clusters:
      targetObjectRef:
        apiVersion: v1
        kind: Secret
        name: {{ .Values.clusterName }}-cluster-secret
      patchTemplate: |
        metadata:
          labels:
            {{ "{{ (index . 1).metadata.labels }}" }}
      patchType: application/merge-patch+json
      sourceObjectRefs:
      - apiVersion: hive.openshift.io/v1
        kind: ClusterDeployment
        name: {{ .Values.clusterName }}
        namespace: {{ .Values.clusterName }}