apiVersion: redhatcop.redhat.io/v1alpha1
kind: Patch
metadata:
  name: patch-label-argocd-clusters
  namespace: openshift-gitops
spec:
  serviceAccountRef:
    name: default
  patches:
    patch-gitops-clusters:
      targetObjectRef:
        apiVersion: v1
        kind: Secret
        name: {{ .Values.clusterName }}-cluster-secret
      patchTemplate: |
        metadata:
          labels:
            hive.openshift.io/cluster-platform: {{ '{{ (index . 1).metadata.labels.hive\.openshift\.io/cluster-platform }}' }}
            hive.openshift.io/version-major: {{ '{{ (index . 1).metadata.labels.hive\.openshift\.io/version-major" }}' }}
            hive.openshift.io/version-major-minor: {{ '{{ (index . 1).metadata.labels.hive\.openshift\.ioversion-major-minor" }}' }}
      patchType: application/merge-patch+json
      sourceObjectRefs:
      - apiVersion: hive.openshift.io/v1
        kind: ClusterDeployment
        name: {{ .Values.clusterName }}
        namespace: {{ .Values.clusterName }}